version: '3.8'

services:
  postgres:
   image: postgres:latest
   container_name: local_postgres
   restart: unless-stopped
   ports:
     - "5432:5432"
   environment:
     POSTGRES_PASSWORD: almog1is2the3best4
     POSTGRES_DB: bot
   volumes:
     - ./.data/pgdata:/var/lib/postgresql/data
